/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ec.fin.austro.view;

import ec.fin.austro.view.component.DemoCustomTab1;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import javax.swing.JTabbedPane;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;

/**
 *
 * @author ba0100068f
 */
public class MainPrincipal1 extends javax.swing.JFrame {

    private Integer idTab = 1;

    public JTabbedPane getjTabbedPaneDinamico() {
        return jTabbedPaneDinamico;
    }

    int numTabs;

    /**
     * Creates new form MainPrincipal
     */
    public MainPrincipal1() {
        setLocationRelativeTo(null);
        initComponents();
        // Assuming "icon.png" is your icon image file in the project root directory
        ImageIcon icon = new ImageIcon(getClass().getResource("/header.png"));
        setIconImage(icon.getImage());
        jTabbedPaneDinamico.setFont(new java.awt.Font("Segoe UI", 1, 12));
        jTabbedPaneDinamico.add(new TabcustomEDJPanel(idTab), " Nuevo " + idTab + "    ", 0);
        /* add first tab */
        //jTabbedPaneDinamico.add(createJPanel(), "Tab " + String.valueOf(numTabs), numTabs++);
        jTabbedPaneDinamico.setTabComponentAt(0, new DemoCustomTab1(this));
        /* add tab to add new tab when click */
        jTabbedPaneDinamico.add(new JPanel(), "+", 1);
        jTabbedPaneDinamico.addChangeListener(changeListener);
        numTabs=2;
        idTab++;
    }

    ChangeListener changeListener = new ChangeListener() {
        @Override
        public void stateChanged(ChangeEvent e) {
            addNewTab();
        }
    };

    private void addNewTab() {
        int index = numTabs - 1;
        int selin=jTabbedPaneDinamico.getSelectedIndex();
        if (jTabbedPaneDinamico.getSelectedIndex() == index) {
            /* if click new tab add new tab */
            jTabbedPaneDinamico.setFont(new java.awt.Font("Segoe UI", 1, 12));
            jTabbedPaneDinamico.add(new TabcustomEDJPanel(idTab), "Nuevo " + idTab, index);
            /* set tab is custom tab */
            jTabbedPaneDinamico.setTabComponentAt(index, new DemoCustomTab1(this));
            jTabbedPaneDinamico.removeChangeListener(changeListener);
            jTabbedPaneDinamico.setSelectedIndex(index);
            jTabbedPaneDinamico.addChangeListener(changeListener);
            numTabs++;
            idTab++;
        }
    }

    public void removeTab(int index) {
        jTabbedPaneDinamico.remove(index);
        numTabs--;
        if (index == numTabs - 1 && index > 0) {
            jTabbedPaneDinamico.setSelectedIndex(numTabs - 2);
        } else {
            jTabbedPaneDinamico.setSelectedIndex(index);
        }
        if (numTabs == 1) {
            addNewTab();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPaneDinamico = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jToolBar2 = new javax.swing.JToolBar();
        jButtonAgregar = new javax.swing.JButton();
        jButtonEliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPaneDinamico.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        jTabbedPaneDinamico.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTabbedPaneDinamico.setOpaque(true);

        jToolBar2.setBackground(new java.awt.Color(204, 204, 204));
        jToolBar2.setRollover(true);

        jButtonAgregar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add.png"))); // NOI18N
        jButtonAgregar.setText("Agregar");
        jButtonAgregar.setFocusable(false);
        jButtonAgregar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButtonAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAgregarMouseClicked(evt);
            }
        });
        jToolBar2.add(jButtonAgregar);

        jButtonEliminar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/delete.png"))); // NOI18N
        jButtonEliminar.setText("Eliminar");
        jButtonEliminar.setFocusable(false);
        jButtonEliminar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButtonEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonEliminarMouseClicked(evt);
            }
        });
        jToolBar2.add(jButtonEliminar);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1055, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTabbedPaneDinamico, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPaneDinamico, javax.swing.GroupLayout.DEFAULT_SIZE, 645, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAgregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAgregarMouseClicked
        idTab++;
        jTabbedPaneDinamico.add(new TabcustomEDJPanel(idTab), " Nuevo " + idTab + "    ", jTabbedPaneDinamico.getTabCount());
    }//GEN-LAST:event_jButtonAgregarMouseClicked

    private void jButtonEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonEliminarMouseClicked

        if (jTabbedPaneDinamico.getTabCount() > 1) {
            jTabbedPaneDinamico.remove(jTabbedPaneDinamico.getSelectedIndex());
        }
    }//GEN-LAST:event_jButtonEliminarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainPrincipal1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainPrincipal1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainPrincipal1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainPrincipal1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainPrincipal1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAgregar;
    private javax.swing.JButton jButtonEliminar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTabbedPane jTabbedPaneDinamico;
    private javax.swing.JToolBar jToolBar2;
    // End of variables declaration//GEN-END:variables
}
